# Generated by Django 4.1.5 on 2023-02-16 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Name post')),
                ('text', models.CharField(max_length=1500, verbose_name='Body post')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 2, 16, 10, 20, 45, 821622, tzinfo=datetime.timezone.utc), verbose_name='Date created')),
            ],
        ),
    ]
