# Generated by Django 4.1.5 on 2023-02-16 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_todo_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 10, 20, 45, 790623, tzinfo=datetime.timezone.utc), verbose_name='Date created'),
        ),
    ]
